server:
  port: 8081
  servlet:
    context-path: /crud  

spring:
  application:
    name: ms-crud
  
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin    

crud:
  rabbitmq:
    exchange: crud.exchange
    routingkey: crud.produto.routingkey
