server:
  port: 8082
  servlet:
    context-path: /pagamento

spring:
  application:
    name: ms-pagamento
  
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin    

crud:
  rabbitmq:
    exchange: crud.exchange
    queue: crud.produto.queue
